
OrdererOrgs:
  - Name: Orderer
    Domain: blockfiler.com
    Specs:
      - Hostname: orderer
        SANS:
          - "localhost"
          - "127.0.0.1"

PeerOrgs:
  - Name: Blockfiler
    Domain: blockfiler.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 0
  
  - Name: Blockfiler2
    Domain: blockfiler2.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 0
