
OrdererOrgs:
  - Name: Orderer
    Domain: empresa.com
    Specs:
      - Hostname: orderer
        SANS:
          - "localhost"
          - "127.0.0.1"

PeerOrgs:
  - Name: Empresa
    Domain: empresa.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 0
  
  - Name: CallAtivo
    Domain: callativo.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 0

  - Name: CallReativo
    Domain: callreativo.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 0

